### ISSUE TITLE
Support of IHP PDK

### ISSUE THREAD

**Issue by hpretl** [TinyTapeout/xschem-viewer#10]
It would be great if besides the SKY130 primitive devices also the SG13G2 primitives would be supported. I imagine there could be some kind of auto-detection of the proper PDK by inspecting device names.

**Comment by urish** [comment]
Can you share a link to an example of a schematic using sg13g2?

**Comment by hpretl** [comment]
Sure. It would be ideal if this would work: https://github.com/iic-jku/analog-circuit-design/blob/main/xschem/dc_lv_nmos.sch

As you see when going to this repo, I started working on an analog circuit design class for JKU this fall.

**Comment by urish** [comment]
done!

**Comment by hpretl** [comment]
Wow, that was superfast, I am deeply impressed :-)
