### ISSUE TITLE
Adjust for new standard library path

### ISSUE THREAD

**Issue by mole99** [TinyTapeout/xschem-viewer#13]
Previously, symbols from the standard library were referenced using the `devices/` prefix in sky130. This behavior was changed in a recent PDK version to match the default behavior of xschem. Standard symbols are now referenced without the `devices/` prefix.

For example, `devices/ipin.sym` becomes `ipin.sym`.

An example that shows the issue is this schematic: https://xschem-viewer.com/?file=https%3A%2F%2Fgithub.com%2Fefabless%2Fsky130_pa_ip__instramp%2Fblob%2Fmain%2Fxschem%2Fsky130_pa_ip__instramp.sch

Btw. I really love xschem-viewer, a great tool and so useful!

**Comment by urish** [comment]
Thanks for reporting! Looks like the current version of that file is broken (syntax error on [line 94](https://github.com/efabless/sky130_pa_ip__instramp/blob/35903609acdd49ff7d6f82663059cba1599a63b2/xschem/sky130_pa_ip__instramp.sch#L94)), so I'll test with https://github.com/efabless/sky130_pa_ip__instramp/blob/313bbc11df304a461684ebe26ffdfaa2c11273e1/xschem/sky130_pa_ip__instramp.sch

**Comment by urish** [comment]
Fixed: https://xschem-viewer.com/?file=https%3A%2F%2Fgithub.com%2Fefabless%2Fsky130_pa_ip__instramp%2Fblob%2F313bbc11df304a461684ebe26ffdfaa2c11273e1%2Fxschem%2Fsky130_pa_ip__instramp.sch

**Comment by mole99** [comment]
Thanks a lot @urish!

Fixed the syntax error in the schematic (it seems xschem is much more lax) and can confirm it works again  🎉
