### ISSUE TITLE
Xschem's new RC version numbering seems to break xschem-viewer

### ISSUE THREAD

**Issue by algofoogle** [TinyTapeout/xschem-viewer#14]
Try xschem-viewer.com with: https://github.com/alokerdas/analog/blob/main/opamp.sch

i.e. this URL:
https://xschem-viewer.com/?file=https%3A%2F%2Fgithub.com%2Falokerdas%2Fanalog%2Fblob%2Fmain%2Fopamp.sch

It fails with this error:
```
Error loading https://github.com/alokerdas/analog/blob/main/opamp.sch: SyntaxError: Expected "file_version=", [ \t\n\r], or [0-9.] but "R" found.
```

...possibly due to the `RC` suffix on the xschem `version=2.4.6RC` in the first line of the file:
```sch
v {xschem version=3.4.6RC file_version=1.2
```

**Comment by urish** [comment]
Thanks for reporting, fixed!
