### ISSUE TITLE
load data

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/xschem-viewer#3]
if there is data present (or becomes present during an action?) then it would be cool if the viewer loaded the data in the graphs

**Comment by urish** [comment]
Can you please be more specific?

We're not running spice sim or anything like that, so I'm not sure how data may become present

**Comment by mattvenn** [comment]
I was thinking if there was the .raw file there then it could be  used to fill the graphs. 
![image](https://github.com/TinyTapeout/xschem-viewer/assets/634220/16b4cc47-7112-4126-8548-c81283f35d7a)

**Comment by urish** [comment]
Can you share the link to the .sch file that contains the graph? We need to find out if it includes enough info to locate the .raw file

**Comment by mattvenn** [comment]
https://github.com/mattvenn/tt06-analog-r2r-dac/blob/main/xschem/testbench.sch#L168
also added the raw file. they're quite big and not very compressible, so don't know if it's a great idea

**Comment by urish** [comment]
Yeah, it's about 40MB, not a great experience (esp. on mobile browser). Could probably be solved with a server side rendering of the graph, but that would add a bunch of complexity to the app, and I'm not sure how common it is to include the .raw file in the repo.

**Comment by mattvenn** [comment]
ok, let's close this for now.
