### ISSUE TITLE
Support `spice_ignore` render

### ISSUE THREAD

**Issue by smunaut** [TinyTapeout/xschem-viewer#6]
See https://xschem-viewer.com/?file=https%3A%2F%2Fgithub.com%2Fengrvip123%2Ftt_um_vks_pll%2Fblob%2Fmain%2Fxschem%2Fcp%2Fcp.sch

versus how xschem renders it

![2024-04-11_884x444_scrot](https://github.com/TinyTapeout/xschem-viewer/assets/129013/be101979-062c-438b-a3d9-baa23ec4caaa)

That element has the `spice_ignore=true` attribute on it.

**Comment by urish** [comment]
Done!
